/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects.
// It is included here so the Wave 5 Phase 1B build pack is complete on first unzip.
