export default function ActivatePage() {
  return (
    <main className="form-wrap">
      <section className="form-card">
        <h1>Activate Device</h1>
        <p className="notice">Device activation is handled by the protected Wave 5 Phase 1B API foundation.</p>
        <p>Use <code>POST /api/devices/activate</code> with an activation code, device name, optional device identifier, and optional assigned location.</p>
        <p>Activation codes are generated by authorised users through <code>POST /api/devices/activation-code</code>.</p>
      </section>
    </main>
  );
}
